spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521/orcl
    username: rm560593
    password: 100225
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  # ðŸ“§ CONFIGURAÃ‡ÃƒO DE E-MAIL PARA PRODUÃ‡ÃƒO (GMAIL)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME:vliraruggeri@gmail.com}
    password: ${SMTP_PASSWORD:sua-senha-de-app-aqui}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    test-connection: false
seed:
  enabled: true
jwt:
  secret: ${JWT_SECRET}
otel:
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://signoz:4317}
  export:
    enabled: true
logging:
  level:
    root: INFO
    org.springframework.mail: DEBUG
    com.backend.humainzedash: DEBUG

